AWSTemplateFormatVersion: '2010-09-09'
Description: Infraestrutura básica Abstergo

Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: abstergo-data-bucket

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: abstergo-template
      LaunchTemplateData:
        InstanceType: t2.micro
        ImageId: ami-0c55b159cbfafe1f0

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: '1'
      MaxSize: '3'
      DesiredCapacity: '1'